version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bbb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
