"""Create subscribers table

Revision ID: 42334e50263a
Revises: 
Create Date: 2024-09-25 00:10:48.918281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42334e50263a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('youtube_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('subscriber_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('youtube_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
